### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by cljnilsson** [oskosk/express-socket.io-session#25]
Trying to let the code speak for itself.
```
var express = require("express");
var app = express();
var server = require("http").createServer(app);
var io = require("socket.io")(server);
var session = require('express-session')({
    name: "session",
    secret: "lfdod9Jiru65MMl",
    saveUninitialized: true,
    resave: true,
    cookie: {
        httpOnly: false,
        maxAge: 1000 * 60 * 60 * 24
    }
});
var sharedsession = require("express-socket.io-session");

app.use(session);
io.use(sharedsession(session), {
    autoSave:true
});
io.on('connection', function(socket){
    socket.on("clicked", function(value) {
       // this does happen, I checked with console.logs
       socket.handshake.session.key = value;
    });
});
`app.get("/index", function(req, res) {
    console.log("xxx");
    console.log(req.session.key); //writes undefined
    res.render("index");
});
```

**Comment by matt-mcdaniel** [comment]
I'm having the same issue, running express 4.14.0 and node 7.6.0, and express-session 1.15. Express doesn't seem to know about the saved session variables.

**Comment by arthurlacoste** [comment]
Are you tried to use  `next();`, [like in this exemple](https://github.com/oskosk/express-socket.io-session/blob/master/example/index.js) ?

**Comment by matt-mcdaniel** [comment]
@oskosk not sure what happened to your message, but I tried using `next()` before specifying the routes but to no avail. I've updated the repo linked in my above message to reflect that.

**Comment by ashnamuh** [comment]
I'am also having the same issue!

**Comment by CharlesMeyer24** [comment]
Same here! have you find another library to share session between socket and express-session

**Comment by fadsel** [comment]
So it seems that everyone is experiencing this 😞

**Comment by fadsel** [comment]
**Now It works!** - So for anyone experiencing this :face_with_thermometer: , you should try to `save()` while you are your `socket events` , that way you can access the **session** even in express routes!

- Cheers!

**Comment by CharlesMeyer24** [comment]
Still not work at home. What did you add to the code ?

**Comment by fadsel** [comment]
@CharlesMeyer24  this line `socket.handshake.session.save();`

**Comment by CharlesMeyer24** [comment]
Yhé that s what i did but my key still remains undefined x) ...

**Comment by fadsel** [comment]
Hmmm... Thats weird , Are you using multiple sub domains , perhaps with same cookie name by any chance?

If thats the case , Lets try using isolating your **namespaces**,
As in instead of this
```
io.use(sharedsession(session, {
	autoSave:true
}));
```

use , lets say ... this
```
io.of('/write-anything').use(sharedsession(session, {
	autoSave: true
}));
```

Then share your result , if you don't know anything about **namespaces** , you better start using them , they will save you alot of **time**

**Comment by CharlesMeyer24** [comment]
I'm not using multiple sub domains, but just trying to test a simple example.
But I've tried  to use namespace like this

io.of('/write-anything').use(sharedsession(session, {
	autoSave: true;
})).on('connection', function(socket){
  console.log('someone connected');
  socket.handshake.session.key = "something";
  socket.handshake.session.save();
});

app.get("/", function(req, res) {
    console.log(req.session.key); 
    res.render("main");
});

and the output is:

someone connected 
/*When i refresh my main page*/
undefined

I don't know where can come from my problem, but thanks for helping me :)

**Comment by fadsel** [comment]
How do you **connect** to your socket from the client side?
as in `example.com:1234/your-namespace`? or directly to your default **namespace**?

That might be the cause of your problem 👍 
You see ... you are setting the` session variables` on a different namespace , 

It wont work that way, try doing it on the _same namespace_ , as in they are isolated , that's why you are getting **`undefined`** ,
 
Hope it helps

Cheers!

**Comment by CharlesMeyer24** [comment]
I'm well connecting on the same namespace, as i got the message 'someone connected' when i get connected. 
Here is my complete server code:

var express = require("express");
var app = express();
var server = require("http").createServer(app);
var io = require("socket.io")(server);

/* Using the .html extension instead of
	having to name the views as *.ejs */ 
app.engine('.html', require('ejs').__express);

/* Set the folder where the pages are kept */
app.set('views', __dirname + '/views');

/* This avoids having to provide the 
	extension to res.render()*/
app.set('view engine', 'html');

var session = require('express-session')({
    name: "session",
    secret: "lfdod9Jiru65MMl",
    saveUninitialized: true,
    resave: true,
    cookie: {
        httpOnly: false,
        maxAge: 1000 * 60 * 60 * 24
    }
});
var sharedsession = require("express-socket.io-session");

app.use(session);

io.of('/write-anything').use(sharedsession(session, {
	autoSave: true
})).on('connection', function(socket){
  console.log('someone connected');
  socket.handshake.session.key = "something";
  socket.handshake.session.save();
});

app.get("/", function(req, res) {
    console.log(req.session.key); 
    res.render("main");
});

server.listen(8080);

and client code(main.html):


<script src="/socket.io/socket.io.js"></script>
<p>Something</p>
<script>
	var socket = io('http://localhost:8080/write-anything');
</script>

Tell me if you see something wrong with it.
Thanks man!

Cya

**Comment by djskinner** [comment]
Did you ever get to the bottom of this? I'm having the same issue.

**Comment by fadsel** [comment]
Can you try to access **Express routes** first before you start accessing **Socket events** and vice versa , _Plus share your results?_ 

Do you experience the same problem on both scenarios? 
Are you sure that you are not experiencing an error relating to your browser? perhaps a different cookie name or you did not clear your cache e.t.c

**Comment by djskinner** [comment]
Ok here's what I'm trying to do and what I see. Tested using incognito mode with all cookies cleared.

```
const app = express()
const httpServer = http.createServer(app)
const io = socketIO(httpServer)

// Create redis-backed session store and express middleware
const RedisStore = connectRedis(session)
const redisSessionStore = new RedisStore({ host: config.get('redis.host'), port: config.get('redis.port'), logErrors: true })
const sessionMiddleware = session({
    key: 'connect.sid',
    secret: config.get('secretKeyBase'),
    store: redisSessionStore,
    resave: true,
    saveUninitialized: true,
    cookie: {
        secure: false, // process.env.NODE_ENV !== 'development' && process.env.NODE_ENV !== 'test',
        maxAge: ms(config.get('sessionExpiry'))
    },
})

// Use express-session middleware for express
app.use(sessionMiddleware)

// Use same express-session middleware for socket.io
io.use(sharedsession(sessionMiddleware))

io.on('connection', socket => {
    socket.handshake.session.socket = socket.id
    socket.handshake.session.something = 'something else'
    socket.handshake.session.save((err) => {
        console.log('save session', err)
    })
})

app.use((req, res, next) => {
    console.log(req.session)
    next()
})
```

I'm hitting an express route first. When the socket connection is made I see `save session null` which suggests the changes to the session were successful.

On subsequent calls to express I do not see the additional values logged.

I'll try and make something a bit simpler so I can do a socket first.

**Comment by djskinner** [comment]
Socket first works but in order get that working quickly I had to disable `'passport.socketio'`. Perhaps there is some interference going on here. Will investigate further.

**Comment by djskinner** [comment]
Seems to work without `passport.socketio`. To be honest, after having worked through this I don't think I need `passport.socketio` at all. With `express-socket.io-session` I guess I can see if the user is authenticated by checking for `socket.handshake.session.passport.user` and even check that their JWT expiry at any time.

**Comment by fadsel** [comment]
@djskinner  nice to hear that 👍 , it seems you are going to a _permanent solution_ there , 
I don't know if @CharlesMeyer24  solved his problem though 👍
