### ISSUE TITLE
Update session function

### ISSUE THREAD

**Issue by senica** [oskosk/express-socket.io-session#9]
Would be nice to be have a built-in function to grab the current session data if it is modified outside the sockets. In my case, I had an ajax call modifying the session data. 

I ended hacking something like this to update the room data:

```
function updateSocketSessions(room, callback){
    var count = 0;
    var unique = [];
    var clients = Object.keys( ((((((io || {}).nsps || {})['/'] || {}).adapter || {}).rooms || {})[room] || {}) );
    clients.forEach(function(id, index, arr){
      var socket = (io.sockets.connected[id] || {}).handshake || {};
      if(unique.indexOf(socket.sessionID) > -1)
        return false;
      unique.push(socket.sessionID);
      socket.sessionStore.get(socket.sessionID, function(err, data){
        count++;
        socket.session = data;
        if(count >= clients.length){
          callback();
        }
      });
    });
  }
```

**Comment by oskosk** [comment]
Hi Senica. It' supposed to work if you alter session outside the socket. I
mean, if you update from inside an express middleware/route handler

**Comment by oskosk** [comment]
I'll check this and If it's not working I'll patch it

**Comment by senica** [comment]
I assumed that was suppose to be the case, but it was not working for me:
Here's a test handler that is called via ajax:
```
app.post('/signin', function(req, res, next){
      var body = req.body;
      if(!body.name) // We don't enforce the email now  || !body.email
        return res.status(400).json([]);
      req.session.name = sanitize(body.name);
      req.session.email = sanitize(body.email);
      res.json(body);

      req.session.save(function(){
        getClientsFromRoom(req.session.discussion, function(clients){
          io.sockets.in(req.session.discussion).emit('clients', clients);
        });
      });
    });
```

I'm shooting out a message to all clients when someone "signs on" to notify them. I thought perhaps I was doing it too early and express-socket.io-session did not have time to "refresh" the session object (wasn't sure if you were requesting from database or just from the session object itself). So, I even tried adding another request after the client received the ajax response back, and then have the client request via websocket to send to all other clients.  Nothing seemed to work.

Note: I'm using connect-mongo for sessions, not redis. Not sure if that matters.

**Comment by 360disrupt** [comment]
I have the same issue. I push all my logged in users to a list to see how many users are currently logged in. After a user logged in I `emit` a msg `loggedIn`. 

Unfortunately after the user logs in with passport, the session in the socket is not updated unit
- a user reloads the page
- a user opens a new tab
otherwise `newSocket.handshake.session.passport` stays `{}` 

```
io.on 'connection', (newSocket) ->
  socket = newSocket
  ...
  socket.on 'loggedIn', () ->
    console.log chalk.bgMagenta JSON.stringify(newSocket.handshake.session)
```

**Comment by tcstory** [comment]
@360disrupt I met the same problem,I'm coding a online chat room, when people first access the chat room, they will be known as visitor, after they login, they will be known as register user, when they login, I will modity the session to log the register user info,but in the req.handshake.session, i will always store old info until i refresh the page,

**Comment by chumager** [comment]
I've fixed it guys, the problem is generated because the module loads the info when it's connected, later, it only saves modifications.

to accomplish the result needed just put a `session.reload` inside de onevent call.

like this: (don't know how to refffer a code segment, sorry, but the code from the module is really small, so you can find it)

```
    if (options.autoSave === true) {
      debug("Using autoSave feature. express-session middleware will be called on every event received")
      socket.onevent = function() {
        debug("Executing socket.onevent monkeypatched by express-socket.io-session");
        var _args = arguments;
        originalHash = savedHash = hash(req.session);
        cookieId = req.sessionID;
        originalId = req.sessionID;
        //TODO first reload the info from the session handler, then operate the event, finally save the data. 
        req.session.reload(err=>{
            if(err) DoWhatYouWant(err);
            _onevent.apply(socket, _args);
            if (shouldSave(req)) {
                req.session.save()
            }
        });
      };
    }

```
if you find some other way, please share :+1:

**Comment by tcstory** [comment]
@chumager thanks

**Comment by chumager** [comment]
Ok guys, I've made a function to resolve my needs, it needs this module to operate, because it do what it does well, so no need to change it.
it has a couple of things that you may not need, but I have to put this function inside a mi middleware who sets the session for express so I have to execute this middleware only once, even if my site updates the session several times per request.

As far as I saw you **MUST** use the session inside your event `socket.on` otherwise it wouldn't refresh the session data, maybe it's a bind problem, but I don't care for now.

It fixes several problems:

- update the storage cookie expires and TTL from storage (redis).
- keep the data between HTTP, AJAX and WS consistent.
- update the cookie in the client (tricky because you hace to use client-server scripts).

BTW `Log` es **my** console logger, you should discard it.

Server side:
`function mysession(socket,next){
    let req = socket.handshake;
    let data = {err:"no session",status:440};
    if(!req.mysession){
        req.mysession=true;
        if(req.session){
            let _onevent = socket.onevent;
            socket.onevent = (... _args)=>{
                req.session.reload(err=>{
                    if(err){//we couldn't retreive, advice and disconnect
                        Log.error("MYSESSION","error loading session");
                        socket.emit("ERROR",data);
                        socket.disconnect();
                    }else{//we have the new data from the sessión.
                        req.session.touch();//update expires info
                        _onevent.apply(socket,_args);//replicate onevent behavion
                        updateSession(socket,req);//inform to my client to update sessión
                    }
                });
            };
        }else{
            Log.error("MYSESSION","no session");
            socket.emit("ERROR",data);
            socket.disconnect();
        }
    }
    next();
}
function updateSession(socket,req){
    let cookie = req.session.cookie;
    let hostname = req.headers.host.split(':')[0];
    let key = `${hostname}.sid`;
    //TODO key is to find MY OWN session key, use yours at will
    let value = req.cookies[key].replace(':','%3A');//":" is no an accepted char, ain't want to to use url parser, just change this if you want 
    socket.emit("renew-cookie", `${key}=${value};expires=${cookie._expires.toUTCString()};path=${cookie.path}`);
}
`

Client side:
`socket.on('renew-cookie',data=>{
    document.cookie=data;
});
`

Client side is just in case you want to keep your cookie updated.

example:

Server side:
`
io.use(sharedsession(session,{autoSave:true}));
io.use(mysession);
io.on('connection', function(socket){
    socket.on('session', function(){//ain't bother for session error, it was handled in the middleware
//session is any event, the name is just a reference 
        let sess = socket.handshake.session;//keep session inside your event
        if(!sess.views) sess.views=0;
        sess.views++;
        socket.emit('session',sess);
    });
});
`

Client side, no standard lines added (I'm lazy)

`                
$("#session").on('click',ev=>{
    socket.emit('session');
});
socket.on('session',data=>{
    console.log(data);
    console.log(document.cookie);
});
`

As you can see, it's too few code to make a module, so that's why I putted here, although It could be added to this module

**Comment by jumika** [comment]
Simply call session.reload()
Like:

> socket.on('send-message', function(data) {
            if(err) return handleError(err);
            socket.handshake.session.reload(function(err) {
                console.log(socket.handshake.session);
            });
        });

**Comment by Zealder-Jude** [comment]
I'm experiencing the same issue. Calling `session.reload()' doesn't work for me. Is there any plans to fix this bug?
